comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

ignore:
  - "internal/pkg/config"
  - "internal/app/router"
  - "internal/app/app.go"
  - "internal/pkg/helpers"  
  - "internal/pkg/protocols"
  - "test"