database:
  driver: "sqlite"
  dbname: "vanir.db"
  username: "bruno"
  password: "123456"
  host: "localhost"
  port: "5432"
  max_lifetime: 7200
  max_open_conns: 150
  max_idle_conns: 50

server:
  port: "3333"
  secret: "jdnfksdmfksda"