name: build
run-name: build, push and deploy ${{ github.event.pull_request.head.ref }}

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build:
    name: "build"
    runs-on: ubuntu-20.04
    steps:
      - name: get repository files
        uses: actions/checkout@v3
      - uses: codfish/semantic-release-action@v2
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: get version
        run: |
          VERSION=v$RELEASE_VERSION
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: docker build and push
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 3
          max_attempts: 3
          command: |
            docker build . -t brunolombardi/vanir:$VERSION -t brunolombardi/vanir:latest
            docker push brunolombardi/vanir:latest
            docker push brunolombardi/vanir:$VERSION
  deploy:
    needs: [build]
    name: "deploy"
    uses: ./.github/workflows/deploy.yml
    secrets: inherit