name: build
run-name: build and push image to registry

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build:
    name: "build"
    runs-on: ubuntu-20.04
    steps:
      - name: get repository files
        uses: actions/checkout@v3
      - name: get version from commit
        run: |
          VERSION=$(git rev-parse --short HEAD)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: docker build
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 3
          max_attempts: 3
          command: |
            docker build . -t brunolombardi/vanir:$VERSION -t brunolombardi/vanir:latest
            docker push brunolombardi/vanir:latest
            docker push brunolombardi/vanir:$VERSION
  deploy:
    needs: [build]
    name: "deploy"
    uses: ./.github/workflows/deploy.yml
    secrets: inherit