name: deploy

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: get repository files
        uses: actions/checkout@v3
      - name: install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: install private ssh key from secrets
        env:
          SSH_KEY: ${{ secrets.DROPLET_PRIVATE_SSH_KEY }}
        run: |
          touch .id_rsa
          echo "$SSH_KEY" >> .id_rsa
          cd ~/.ssh
          touch known_hosts
          cd ..
          ssh-keyscan -H 159.203.116.135 >> ~/.ssh/known_hosts
      - name: Execute docker ps on digital ocean droplet
        run: |
          doctl compute ssh ocean --ssh-key-path="./.id_rsa" --ssh-command="docker ps"