name: deploy

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: get repository files
        uses: actions/checkout@v3
      - name: install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DROPLET_PRIVATE_SSH_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.DROPLET_KNOWN_HOSTS }}
      - name: Execute docker ps on digital ocean droplet
        run: |
          doctl compute ssh ocean --ssh-command="docker ps"