name: deploy

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: get repository files
        uses: actions/checkout@v3
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Execute docker ps on ocean droplet
        run: |
          doctl compute ssh ocean --ssh-command="docker ps"