name: test
run-name: running unit tests for pull request \#${{ github.event.pull_request.head.ref }}

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.20.2'
      - run: make dependencies
      - run: make tests
