name: test
run-name: running unit tests for pull request \#${{ github.event.pull_request.head.ref }}

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: get repository files
        uses: actions/checkout@v3
      - name: setup go environment
        uses: actions/setup-go@v3
          with:
            go-version: '^1.20.2'
      - name: download dependencies
        run: make dependencies
      - name: run unit tests
        run: make tests
      - name: upload coverage report
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.out
          flags: unittests
          name: codecov-umbrella
